spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@cluster0.b8jiiet.mongodb.net/:${DB_NAME:webFlux}?retryWrites=true&w=majority&appName=Cluster0
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: webflux